//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by zombie.rc
//
#define IDC_MYICON                      2
#define IDD_ZOMBIE_DIALOG               102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDI_ZOMBIE                      107
#define IDI_SMALL                       108
#define IDC_ZOMBIE                      109
#define IDR_MAINFRAME                   128
#define IDB_PERSON1                     131
#define IDB_PERSON2                     133
#define IDB_PERSONLEFT2                 134
#define IDB_PERSONLEFT1                 135
#define IDB_HEADRIGHT                   136
#define IDB_HEADLEFT                    137
#define IDB_TREE                        138
#define IDB_CLOUD                       139
#define IDB_SMALLZOMBIEL1               140
#define IDB_SMALLZOMBIEL2               141
#define IDB_SMALLZOMBIER1               142
#define IDB_SMALLZOMBIER2               143
#define IDB_DESERTEAGLER                146
#define IDB_DESERTEAGLEL                147
#define IDB_DEBULLET                    150
#define IDB_BLOODOUT                    151
#define IDB_BLOODOUTR                   152
#define IDB_BLOODOUTUP                  153
#define IDB_INITIALIZE                  155
#define IDB_START                       156
#define IDB_STARTSMALL                  157
#define IDB_OPERATESMALL                158
#define IDB_OPERATE                     159
#define IDB_MSG_DESERTEAGLE             160
#define IDB_GRASS                       161
#define IDB_SMALLZOMBIEDIEL             163
#define IDB_SMALLZOMBIEDIER             165
#define IDB_MSG_AK47                    166
#define IDB_AK47RIGHT                   167
#define IDB_AK47LEFT                    168
#define IDB_ROOMDOOR                    169
#define IDB_MSG_M4A1                    170
#define IDB_M4A1RIGHT                   171
#define IDB_M4A1LEFT                    172
#define IDB_AWPRIGHT                    173
#define IDB_MSG_AWP                     174
#define IDB_AWPLEFT                     175
#define IDB_FIVESEVENRIGHT              176
#define IDB_MSG_FIVESEVEN               177
#define IDB_FIVESEVENLEFT               178
#define IDB_USPRIGHT                    179
#define IDB_MSG_USP                     180
#define IDB_USPLEFT                     181
#define IDB_MP5RIGHT                    182
#define IDB_MSG_MP5                     183
#define IDB_MP5LEFT                     184
#define IDB_CUTDOWNTREE                 185
#define IDB_DEADTREE                    186
#define IDB_SMALLCAR                    187
#define IDB_KEY                         189
#define IDB_BIRDFLYR                    194
#define IDB_BIRDONTREE                  195
#define IDB_BIRDFLYR1                   196
#define IDB_BIRDFLYL                    197
#define IDB_BIRDFLYL1                   198
#define IDB_DEADBIRD                    199
#define IDB_DEADBIRDR                   200
#define IDB_ARROW                       201
#define IDB_BOW                         202
#define IDB_MSG_BOW                     203
#define IDB_PAPER                       204
#define IDB_SELECTBKG1                  205
#define IDB_OKSMALL                     206
#define IDB_OK                          207
#define IDB_HOUSE1                      208
#define IDB_SELECTBKG2                  209
#define IDB_WINDOW1                     210
#define IDB_DEADMAN1                    211
#define IDB_CABINETOPEN                 212
#define IDB_CABINETCLOSE                213
#define IDB_SELECTBKG3                  214
#define IDB_SELECTBKG4                  215
#define IDB_OPERATEBKG                  216
#define IDB_SELECTBKG5                  217
#define IDB_BULLETSUPPLY                218
#define IDB_ROADSIGN                    219
#define IDB_BUS                         220
#define IDB_BUSDOOR                     221
#define IDB_BUSFRONTDOOR                222
#define IDB_CLOSESTOOL                  223
#define IDB_BED                         224
#define IDB_TV                          225
#define IDB_SOCKET1                     226
#define IDB_SOCKET2                     227
#define IDB_DISK                        228
#define IDB_CALENDAR                    229
#define IDB_PAPERBKG1                   230
#define IDB_WASHPOT                     231
#define IDB_SAFEBOX                     232
#define IDB_SAFEBOXBKG                  233
#define IDB_NUM0                        235
#define IDB_NUM1                        236
#define IDB_NUM2                        237
#define IDB_NUM3                        238
#define IDB_NUM4                        239
#define IDB_NUM5                        240
#define IDB_NUM6                        241
#define IDB_NUM7                        242
#define IDB_NUM8                        243
#define IDB_NUM9                        244
#define IDB_SAFEBOXOKSMALL              245
#define IDB_SAFEBOXOK                   246
#define IDB_SOFA                        247
#define IDB_DESK                        248
#define IDB_FOOTBALL                    249
#define IDB_MESSIPAPER                  250
#define IDB_BITMAP2                     251
#define IDB_MESSIBKG                    251
#define IDB_HOME                        252
#define IDB_MENTALDOOR                  254
#define IDB_DOGRIGHT1                   256
#define IDB_DOGRIGHT2                   257
#define IDB_DOGRIGHT3                   258
#define IDB_DOGRIGHT4                   259
#define IDB_DOGRIGHT5                   260
#define IDB_DOGRIGHT6                   261
#define IDB_DOGRIGHT7                   262
#define IDB_DOGLEFT1                    264
#define IDB_DOGLEFT2                    265
#define IDB_DOGLEFT3                    266
#define IDB_DOGLEFT4                    267
#define IDB_DOGLEFT5                    268
#define IDB_DOGLEFT6                    269
#define IDB_DOGLEFT7                    270
#define IDB_PASSSTAGE1BKG               271
#define IDB_PAPERBKG2                   272
#define IDB_PAPERBKG3                   273
#define IDB_STICK                       274
#define IDB_CLOSESTOOLBKG               275
#define IDB_DOGDEADR                    276
#define IDB_DOGDEADL                    277
#define IDB_TVSNOWBKG2                  278
#define IDB_TVSNOWBKG1                  279
#define IDB_BUSSET                      280
#define IDB_TRUCK                       281
#define IDB_TRUCK1                      282
#define IDB_BIKE                        283
#define IDB_BUIDING                     284
#define IDB_GAMEMACHINE                 285
#define IDB_GAMEMACHINEBKG              286
#define IDB_SMALLEXITBKG                287
#define IDB_BIGEXITBKG                  288
#define IDB_SMALLINSERTCOIN             289
#define IDB_BIGINSERTCOIN               290
#define IDB_BTNNOTON                    291
#define IDB_BTNON                       292
#define IDB_COIN                        293
#define IDB_ROADDIRECTLIGHT             294
#define IDB_ROADDIRECTLIGHT1            295
#define IDB_GAMEROOM                    296
#define IDB_CLOUD1                      298
#define IDB_LADDER                      299
#define IDB_GAMEMACHINE2                300
#define IDB_GAMEMACHINE1                301
#define IDB_PLAYERBAGBKG                302
#define IDB_EQUIPSMALL                  303
#define IDB_DROPBIG                     304
#define IDB_EQUIPBIG                    305
#define IDB_DROPSMALL                   306
#define IDB_BAGBKGNOTON                 307
#define IDB_BAGBKGON                    308
#define IDB_MASK1                       309
#define IDB_MASK2                       310
#define IDB_MASKROOM                    311
#define IDB_MP5BKG                      312
#define IDB_GETSMALL                    313
#define IDB_GETBIG                      314
#define IDB_BLOODSUPPLY1                315
#define IDB_HUNTERCLIMBL1               316
#define IDB_HUNTERCLIMBL2               317
#define IDB_HUNTERCLIMBR2               318
#define IDB_HUNTERCLIMBR1               319
#define IDB_HUNTERDIEDR                 320
#define IDB_SPIDER_S1                   321
#define IDB_SPIDER_S2                   322
#define IDB_SPIDER_SD                   323
#define IDB_SPIDER_B                    324
#define IDB_SPIDER_B_GR                 325
#define IDB_SPIDER_B_GL                 326
#define IDB_BIGSPIDERDEAD               327
#define IDB_WEAPONROOM                  328
#define IDB_WEAPONSHELF                 329
#define IDB_WINDOW2                     330
#define IDB_DOOR1                       331
#define IDB_WINDOWCRACK                 332
#define IDB_WINDOWBROKEN                333
#define IDB_SPIDERBLOOD                 334
#define IDB_STAGE3_PAPER1               335
#define IDB_STAGE3_PAPER2               336
#define IDB_BITMAP1                     337
#define IDB_PASSSTAGE3BKG               337
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        338
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
